const address = '河南省信阳市商城县伏山乡杨桥村民委员会入口处深山绿茶'

export const siteConfig = {
  brandName: '山野本味',
  tagline: '绿茶、黑木耳与山野副产',
  phone: '131-3764-2260',
  wechat: 'liushoufu13137642260',
  wechatQr: '/images/wechat-qr.svg',
  address,
  mapLink: `https://uri.amap.com/search?keyword=${encodeURIComponent(address)}`,
  features: {
    showPrices: false,
    showMessagesPage: false,
  },
}

export const tipsSections = [
  {
    id: 'tea-brewing',
    title: '茶叶怎么冲泡',
    summary: '绿茶建议用干净的水、透明玻璃杯或盖碗，水温不要太高。',
    items: [
      '用水建议：纯净水、山泉水优先，尽量不用有明显异味的水。',
      '杯具建议：玻璃杯适合看茶形，盖碗适合更细致地控制冲泡。',
      '水温建议：绿茶一般用 80 到 90 度左右热水，不建议直接用沸水烫。',
      '投茶建议：普通玻璃杯一次放 3 到 5 克，按个人口味可略微增减。',
      '冲泡建议：先润杯，再注水，前两泡口感更鲜爽，后面可继续续水。',
    ],
    notes: ['现喝现泡口感更好。', '夏天可冷泡，口感更清爽。'],
  },
  {
    id: 'kudzu-mixing',
    title: '葛根粉怎么冲制',
    summary: '葛根粉冲制时先用少量凉水调匀，再用开水快速冲熟。',
    items: [
      '先舀适量葛根粉到碗里，加入少量凉水搅成均匀粉浆。',
      '再边倒开水边快速搅拌，直到变得透亮、浓稠。',
      '可按个人口味加入蜂蜜、白糖、红枣水等搭配食用。',
      '早晚都可以作为家常冲饮，热饮口感更顺滑。',
    ],
    notes: ['很多人会把葛根粉当作家常冲饮。', '建议现冲现喝，口感更细腻。'],
  },
  {
    id: 'acorn-mixing',
    title: '橡子粉怎么冲制',
    summary: '橡子粉适合先调匀再冲开，也可做地方风味食品。',
    items: [
      '先取适量橡子粉，用少量温水或凉水调匀。',
      '再加热水继续搅拌，让口感更顺滑。',
      '可根据习惯做成冲饮，也可搭配主食或地方特色吃法。',
      '如果第一次食用，建议先从少量开始，慢慢调整浓淡。',
    ],
    notes: ['橡子粉口感更有山野风味。', '适合作为家常冲饮或特色搭配。'],
  },
]

export const heroSlides = [
  {
    id: 'tea',
    title: '高山绿茶，鲜爽回甘',
    description: '清明前绿茶、雪芽、一芽一叶和一芽两叶都支持按斤选购与包装搭配。',
    image: '/images/products/green-tea/xueya-dry.avif',
    productSlug: 'gaoshan-lvcha-xueya',
  },
  {
    id: 'fungus',
    title: '椴木黑木耳，肉厚脆嫩',
    description: '春耳、冬耳可按半斤、一斤搭配袋装或礼盒，适合家用和送礼。',
    image: '/images/products/heimuer/heimuer-winter-dry.avif',
    productSlug: 'duanmu-chuner-hei-muer-winter',
  },
  {
    id: 'gift',
    title: '葛根粉等副产，可按需求配包装',
    description: '葛根粉、橡子粉、茶油和土鸡蛋都可单买，也可按实际需求组合咨询。',
    image: '/images/products/gegenfen/gegengfen-dry.avif',
    productSlug: 'mountain-kudzu-powder',
  },
]

export const categories = [
  {
    id: 'green-tea',
    name: '绿茶',
    description: '按采摘时间查看不同绿茶。',
    tags: ['清明前', '清明', '谷雨'],
  },
  {
    id: 'black-fungus',
    name: '椴木黑木耳',
    description: '按春耳、冬耳查看木耳。',
    tags: ['春耳', '冬耳'],
  },
  {
    id: 'kudzu',
    name: '葛根粉',
    description: '查看葛根粉干品、冲调和包装。',
    tags: ['袋装', '盒装'],
  },
  {
    id: 'acorn',
    name: '橡子粉',
    description: '查看橡子粉成品与冲调展示。',
    tags: ['袋装', '盒装'],
  },
  {
    id: 'tea-oil',
    name: '茶油',
    description: '查看山茶油和礼盒搭配。',
    tags: ['瓶装', '礼盒'],
  },
  {
    id: 'eggs',
    name: '农家土鸡蛋',
    description: '查看土鸡蛋现货与家庭装。',
    tags: ['农家', '新鲜'],
  },
  {
    id: 'packaging',
    name: '包装',
    description: '袋装、铁盒、礼盒都可单独查看。',
    tags: ['袋装', '铁盒', '礼盒'],
  },
]

export const packagingProducts = [
  {
    id: 'pack-tea-bag-100g',
    kind: 'packaging',
    slug: 'pack-tea-bag-100g',
    name: '茶叶袋装 100g',
    category: '包装',
    subcategory: '袋装',
    packagingType: '袋装',
    capacity: '100g',
    summary: '适合试喝、小分量送人和日常随手拿取。',
    description: '轻便袋装，适合装 100g 茶叶，便于试喝、分装和日常携带。',
    specifications: ['单袋容量：100g', '适合绿茶分装', '可按需求搭配多个袋装'],
    sellingPoints: ['轻便好拿', '适合小份分装', '可配多款绿茶'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/packaging/tea/f51ccba60ae1dd8e867d76c6b76a9805.jpg'],
    packageImages: [],
    applicableProducts: ['gaoshan-lvcha-yiyayiye', 'gaoshan-lvcha-yiyaliangye', 'gaoshan-lvcha-xueya'],
  },
  {
    id: 'pack-tea-bag-500g',
    kind: 'packaging',
    slug: 'pack-tea-bag-500g',
    name: '茶叶袋装 500g',
    category: '包装',
    subcategory: '袋装',
    packagingType: '袋装',
    capacity: '500g（半斤）',
    summary: '常用半斤袋装，适合家庭自饮和日常发货。',
    description: '适合装半斤茶叶，便于现货售卖和日常发货，也方便客户自饮保存。',
    specifications: ['单袋容量：500g（半斤）', '适合绿茶常规售卖', '可按半斤起配'],
    sellingPoints: ['日常走货常用', '容量清晰', '便于储存'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/packaging/tea/f51ccba60ae1dd8e867d76c6b76a9805.jpg'],
    packageImages: [],
    applicableProducts: ['gaoshan-lvcha-yiyayiye', 'gaoshan-lvcha-yiyaliangye', 'gaoshan-lvcha-xueya'],
  },
  {
    id: 'pack-tea-small-tin',
    kind: 'packaging',
    slug: 'pack-tea-small-tin',
    name: '茶叶小铁盒',
    category: '包装',
    subcategory: '铁盒',
    packagingType: '铁盒',
    capacity: '2两',
    summary: '适合装 2 两茶叶，适合送人和单独小规格搭配。',
    description: '小铁盒适合装 2 两茶叶，可单独售卖，也可作为礼盒内包装使用。',
    specifications: ['单盒容量：2两', '适合绿茶', '可用于礼盒内分装'],
    sellingPoints: ['体面好看', '适合送人', '便于礼盒组合'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/packaging/tea/d66a27efd982925fffe1d7ac30ab8629.jpg'],
    packageImages: [],
    applicableProducts: ['gaoshan-lvcha-yiyayiye', 'gaoshan-lvcha-yiyaliangye', 'gaoshan-lvcha-xueya'],
  },
  {
    id: 'pack-tea-large-tin',
    kind: 'packaging',
    slug: 'pack-tea-large-tin',
    name: '茶叶大铁盒',
    category: '包装',
    subcategory: '铁盒',
    packagingType: '铁盒',
    capacity: '半斤',
    summary: '适合装半斤茶叶，适合礼赠和整斤拆分搭配。',
    description: '大铁盒适合装半斤茶叶，适合作为礼赠包装或一斤礼盒中的组合装。',
    specifications: ['单盒容量：半斤', '适合绿茶', '适合礼盒搭配'],
    sellingPoints: ['容量更大', '适合礼赠', '外观更稳重'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/packaging/tea/fa8dd38d7e383ba6726c4ac8c3d58b38.jpg'],
    packageImages: [],
    applicableProducts: ['gaoshan-lvcha-yiyayiye', 'gaoshan-lvcha-yiyaliangye', 'gaoshan-lvcha-xueya'],
  },
  {
    id: 'pack-tea-gift-half-jin',
    kind: 'packaging',
    slug: 'pack-tea-gift-half-jin',
    name: '半斤礼盒（2个小铁盒）',
    category: '包装',
    subcategory: '礼盒',
    packagingType: '礼盒',
    capacity: '半斤',
    summary: '半斤礼盒内放 2 个小铁盒，适合送礼和节日搭配。',
    description: '礼盒总量为半斤，内部搭配 2 个小铁盒，适合节日送礼和亲友往来。',
    specifications: ['礼盒总量：半斤', '内部组合：2个小铁盒', '适合绿茶礼赠'],
    sellingPoints: ['送礼体面', '分装整齐', '适合节日'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: [
      '/images/packaging/four-boxes/b.webp',
      '/images/packaging/tea/d66a27efd982925fffe1d7ac30ab8629.jpg',
    ],
    packageImages: [],
    applicableProducts: ['gaoshan-lvcha-yiyayiye', 'gaoshan-lvcha-yiyaliangye', 'gaoshan-lvcha-xueya'],
  },
  {
    id: 'pack-tea-gift-one-jin-four-small',
    kind: 'packaging',
    slug: 'pack-tea-gift-one-jin-four-small',
    name: '一斤礼盒（4个小铁盒）',
    category: '包装',
    subcategory: '礼盒',
    packagingType: '礼盒',
    capacity: '一斤',
    summary: '一斤礼盒内放 4 个小铁盒，适合正式送礼和多款茶搭配。',
    description: '礼盒总量为一斤，内部放 4 个小铁盒，可做单款或多款绿茶组合。',
    specifications: ['礼盒总量：一斤', '内部组合：4个小铁盒', '适合绿茶礼盒'],
    sellingPoints: ['礼盒层次丰富', '适合组合搭配', '送礼大方'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: [
      '/images/packaging/four-boxes/b.webp',
      '/images/packaging/tea/d66a27efd982925fffe1d7ac30ab8629.jpg',
      '/images/packaging/tea/fa8dd38d7e383ba6726c4ac8c3d58b38.jpg',
    ],
    packageImages: [],
    applicableProducts: ['gaoshan-lvcha-yiyayiye', 'gaoshan-lvcha-yiyaliangye', 'gaoshan-lvcha-xueya'],
  },
  {
    id: 'pack-tea-gift-one-jin-two-large',
    kind: 'packaging',
    slug: 'pack-tea-gift-one-jin-two-large',
    name: '一斤礼盒（2个大铁盒）',
    category: '包装',
    subcategory: '礼盒',
    packagingType: '礼盒',
    capacity: '一斤',
    summary: '一斤礼盒内放 2 个大铁盒，适合整斤装礼赠。',
    description: '礼盒总量为一斤，内部为 2 个大铁盒装，适合需要稳重大方包装的送礼场景。',
    specifications: ['礼盒总量：一斤', '内部组合：2个大铁盒', '适合绿茶礼赠'],
    sellingPoints: ['容量明确', '礼盒体面', '适合走亲访友'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: [
      '/images/packaging/tea/fa8dd38d7e383ba6726c4ac8c3d58b38.jpg',
      '/images/packaging/four-boxes/b.webp',
    ],
    packageImages: [],
    applicableProducts: ['gaoshan-lvcha-yiyayiye', 'gaoshan-lvcha-yiyaliangye', 'gaoshan-lvcha-xueya'],
  },
  {
    id: 'pack-fungus-bag-500g',
    kind: 'packaging',
    slug: 'pack-fungus-bag-500g',
    name: '黑木耳袋装 500g',
    category: '包装',
    subcategory: '袋装',
    packagingType: '袋装',
    capacity: '500g（半斤）',
    summary: '适合椴木黑木耳常规售卖和家用装。',
    description: '适合装半斤黑木耳，便于家庭购买、储存和发货。',
    specifications: ['单袋容量：500g（半斤）', '适合春耳和冬耳', '便于日常发货'],
    sellingPoints: ['常用规格', '发货方便', '家用合适'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/packaging/tea/f51ccba60ae1dd8e867d76c6b76a9805.jpg'],
    packageImages: [],
    applicableProducts: ['duanmu-chuner-hei-muer-spring', 'duanmu-chuner-hei-muer-winter'],
  },
  {
    id: 'pack-gegenfen-bag',
    kind: 'packaging',
    slug: 'pack-gegenfen-bag',
    name: '葛根粉盒装 / 袋装',
    category: '包装',
    subcategory: '袋装',
    packagingType: '袋装',
    capacity: '500g',
    summary: '适合葛根粉常规售卖，可做家用和伴手礼。',
    description: '葛根粉可按 500g 搭配盒装或袋装，适合日常购买和送礼。',
    specifications: ['常用容量：500g', '适合葛根粉', '盒装和袋装可选'],
    sellingPoints: ['日常好带', '适合家用', '可做伴手礼'],
    price: '按需求搭配',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/packaging/gegengfen-box/a.webp'],
    packageImages: [],
    applicableProducts: ['mountain-kudzu-powder'],
  },
]

export const products = [
  {
    id: 'yiyayiye-p1',
    slug: 'gaoshan-lvcha-yiyayiye',
    name: '一芽一叶',
    category: '绿茶',
    subcategory: '清明前',
    summary: '鲜爽明显，适合喜欢芽头细嫩口感的客户。',
    description: '一芽一叶条形匀整，香气清扬，适合按半斤、一斤方式选购。',
    specifications: ['常规售卖：500g（半斤）起', '可配一斤礼盒', '冷藏保存更佳'],
    sellingPoints: ['芽头细嫩', '香气清扬', '适合礼赠'],
    price: '¥498 / 500g',
    showPrice: false,
    featured: true,
    hero: true,
    availablePackaging: ['pack-tea-bag-100g', 'pack-tea-bag-500g', 'pack-tea-small-tin', 'pack-tea-large-tin', 'pack-tea-gift-half-jin', 'pack-tea-gift-one-jin-four-small', 'pack-tea-gift-one-jin-two-large'],
    images: [
      '/images/products/green-tea/yiyayiye.avif',
      '/images/products/green-tea/yiyeyiye-xian.avif',
      '/images/products/green-tea/yiyayiye-taoci.avif',
      '/images/products/green-tea/yiyayiye-taoci1.avif',
      '/images/products/green-tea/yiyayiye-boli.avif',
    ],
    packageImages: ['/images/packaging/four-boxes/b.webp'],
  },
  {
    id: 'yiyaliangye-p1',
    slug: 'gaoshan-lvcha-yiyaliangye',
    name: '一芽两叶',
    category: '绿茶',
    subcategory: '清明前',
    summary: '滋味更饱满，适合日常喝茶和待客。',
    description: '一芽两叶滋味醇和，适合半斤、一斤售卖，也适合做礼盒搭配。',
    specifications: ['常规售卖：500g（半斤）', '也可配一斤礼盒', '冷藏保存更佳'],
    sellingPoints: ['滋味饱满', '耐泡度好', '适合日常待客'],
    price: '¥498 / 500g',
    showPrice: false,
    featured: true,
    hero: true,
    availablePackaging: ['pack-tea-bag-100g', 'pack-tea-bag-500g', 'pack-tea-small-tin', 'pack-tea-large-tin', 'pack-tea-gift-half-jin', 'pack-tea-gift-one-jin-four-small', 'pack-tea-gift-one-jin-two-large'],
    images: [
      '/images/products/green-tea/yiyaliangye.avif',
      '/images/products/green-tea/yiyaliangye-taoci.avif',
      '/images/products/green-tea/yiyaliangye-dry.avif',
      '/images/products/green-tea/yiyaliangye-boli.avif',
    ],
    packageImages: ['/images/packaging/tea/85c39460aa6eb174d99f8270338c9060.jpg'],
  },
  {
    id: 'xueya-p1',
    slug: 'gaoshan-lvcha-xueya',
    name: '雪芽',
    category: '绿茶',
    subcategory: '清明前',
    summary: '芽头肥壮，香气高扬，是目前主推的清明前绿茶之一。',
    description: '雪芽适合按半斤、一斤售卖，可搭配袋装、铁盒和礼盒。',
    specifications: ['常规售卖：500g（半斤）', '一斤可做礼盒', '冷藏保存更佳'],
    sellingPoints: ['芽头漂亮', '香气高扬', '适合送礼'],
    price: '¥498 / 500g',
    showPrice: false,
    featured: true,
    hero: true,
    availablePackaging: ['pack-tea-bag-100g', 'pack-tea-bag-500g', 'pack-tea-small-tin', 'pack-tea-large-tin', 'pack-tea-gift-half-jin', 'pack-tea-gift-one-jin-four-small', 'pack-tea-gift-one-jin-two-large'],
    images: [
      '/images/products/green-tea/xueya-taoci.avif',
      '/images/products/green-tea/xueya-taoci1.avif',
      '/images/products/green-tea/xueya-dry.avif',
      '/images/products/green-tea/xueya-boli.avif',
      '/images/products/green-tea/xueya-boli1.avif',
      '/images/products/green-tea/xueya-xian.avif',
    ],
    packageImages: ['/images/packaging/four-boxes/b.webp'],
  },
  {
    id: 'spring-p4',
    slug: 'duanmu-chuner-hei-muer-spring',
    name: '椴木春耳黑木耳',
    category: '椴木黑木耳',
    subcategory: '春耳',
    summary: '耳片舒展，肉质弹嫩，适合凉拌和家常烹饪。',
    description: '春耳适合按半斤、一斤售卖，家用和送礼都方便。',
    specifications: ['常规售卖：500g（半斤）', '一斤可再配礼袋', '干燥密封保存'],
    sellingPoints: ['泡发率高', '耳片完整', '适合家用'],
    price: '¥168 / 500g',
    showPrice: false,
    featured: true,
    hero: true,
    availablePackaging: ['pack-fungus-bag-500g'],
    images: [
      '/images/products/heimuer/heimuer-dry.avif',
      '/images/products/heimuer/heimuer-pao.avif',
      '/images/products/heimuer/heimuer-wood.avif',
      '/images/products/heimuer/heimuer-wood2.avif',
    ],
    packageImages: [],
  },
  {
    id: 'winter-p4',
    slug: 'duanmu-chuner-hei-muer-winter',
    name: '椴木冬耳黑木耳',
    category: '椴木黑木耳',
    subcategory: '冬耳',
    summary: '肉厚紧实，适合炖煮和礼品搭配。',
    description: '冬耳更厚实，适合按半斤、一斤选购，也可配袋装或礼袋。',
    specifications: ['常规售卖：500g（半斤）', '一斤可再配礼袋', '干燥密封保存'],
    sellingPoints: ['肉厚紧实', '适合炖煮', '礼品搭配方便'],
    price: '¥168 / 500g',
    showPrice: false,
    featured: true,
    hero: true,
    availablePackaging: ['pack-fungus-bag-500g'],
    images: [
      '/images/products/heimuer/heimuer-winter-dry.avif',
      '/images/products/heimuer/heimuer-winter-pao.avif',
      '/images/products/heimuer/heimuer-winter-pao1.avif',
      '/images/products/heimuer/heimuer-winter-wood.avif',
    ],
    packageImages: [],
  },
  {
    id: 'p6',
    slug: 'mountain-kudzu-powder',
    name: '山野葛根粉',
    category: '葛根粉',
    subcategory: '',
    summary: '细粉易冲调，入口顺滑，适合家庭常备。',
    description: '葛根粉以 500g 为常用售卖规格，也可按包装搭配。',
    specifications: ['常规售卖：500g', '袋装或盒装可选', '适合冲调食用'],
    sellingPoints: ['冲调方便', '口感细腻', '家庭常备'],
    price: '¥88 / 500g',
    showPrice: false,
    featured: false,
    hero: false,
    availablePackaging: ['pack-gegenfen-bag'],
    images: [
      '/images/products/gegenfen/gegenfen-eat.avif',
      '/images/products/gegenfen/gegengfen-dry.avif',
      '/images/products/gegenfen/gegenfen-nature.avif',
    ],
    packageImages: ['/images/packaging/gegengfen-box/a.webp'],
  },
  {
    id: 'p7',
    slug: 'mountain-acorn-powder',
    name: '山野橡子粉',
    category: '橡子粉',
    subcategory: '',
    summary: '地方风味明显，适合特色饮食体验。',
    description: '橡子粉以 500g 为常用规格，可按家庭食用需求购买。',
    specifications: ['常规售卖：500g', '可按袋装发货', '适合冲调或做地方风味食品'],
    sellingPoints: ['地方风味', '山野特色', '适合家庭食用'],
    price: '¥96 / 500g',
    showPrice: false,
    featured: false,
    hero: false,
    availablePackaging: [],
    images: [
      '/images/products/xiangzifen/xiangzifen.avif',
      '/images/products/xiangzifen/xiangzifen-dry.avif',
      '/images/products/xiangzifen/xiangzifen-nature1.avif',
      '/images/products/xiangzifen/xiangzifen-nature2.avif',
    ],
    packageImages: [],
  },
  {
    id: 'p8',
    slug: 'cold-pressed-tea-oil',
    name: '冷榨山茶油',
    category: '茶油',
    subcategory: '',
    summary: '清香不腻，适合家庭厨房和礼盒搭配。',
    description: '山茶油目前以瓶装为主，可按家用或礼盒需求搭配。',
    specifications: ['常用规格：500ml', '礼盒规格：1L', '适合凉拌和清炒'],
    sellingPoints: ['冷榨工艺', '清香自然', '适合家用'],
    price: '¥168 / 500ml',
    showPrice: false,
    featured: false,
    hero: true,
    availablePackaging: [],
    images: ['/images/hero-gift.svg'],
    packageImages: ['/images/package-visual.svg'],
  },
  {
    id: 'p9',
    slug: 'farm-eggs',
    name: '农家土鸡蛋',
    category: '农家土鸡蛋',
    subcategory: '',
    summary: '自然喂养，蛋黄浓郁，适合家庭长期采购。',
    description: '土鸡蛋以家庭装为主，适合自用和走亲访友。',
    specifications: ['家庭装：30枚', '大装：60枚', '按新鲜现货发货'],
    sellingPoints: ['农家散养', '新鲜发货', '蛋香浓郁'],
    price: '¥78 / 30枚',
    showPrice: false,
    featured: false,
    hero: false,
    availablePackaging: [],
    images: ['/images/hero-gift.svg'],
    packageImages: ['/images/package-visual.svg'],
  },
]

export const storyHighlights = [
  {
    title: '地址',
    description: address,
  },
  {
    title: '可选包装',
    description: '袋装、铁盒、礼盒都可搭配，适合家用、送礼和走亲访友。',
  },
  {
    title: '主要现货',
    description: '绿茶、椴木黑木耳、葛根粉、橡子粉、茶油、农家土鸡蛋。',
  },
]

export const originStories = [
  {
    title: '茶山环境',
    description: '绿茶来自商城伏山乡一带山场，图片可继续补充采茶、鲜叶和制茶过程。',
    image: '/images/products/green-tea/1172.jpg',
  },
  {
    title: '木耳种植',
    description: '椴木黑木耳可继续补充耳木、干耳、泡发和采收过程图片。',
    image: '/images/products/green-tea/1172.jpg',
  },
]

export const packagingShowcase = [
  {
    title: '袋装与铁盒',
    image: '/images/packaging/tea/f51ccba60ae1dd8e867d76c6b76a9805.jpg',
    description: '茶叶、葛根粉和黑木耳都可按实际容量配袋装或盒装。',
  },
  {
    title: '半斤礼盒',
    image: '/images/packaging/tea/d66a27efd982925fffe1d7ac30ab8629.jpg',
    description: '半斤礼盒可做 2 个小铁盒组合，适合节日送礼。',
  },
  {
    title: '一斤礼盒',
    image: '/images/packaging/four-boxes/b.webp',
    description: '一斤礼盒支持 4 个小铁盒或 2 个大铁盒等方式。',
  },
]

export const defaultInquiries = [
  {
    id: 'inq-demo-1',
    name: '周女士',
    contact: '139****2608',
    product: '高山明前绿茶',
    message: '想了解礼盒规格和起订量。',
    createdAt: '2026-04-11 09:20',
  },
]

export const defaultMessages = [
  {
    id: 'msg-demo-1',
    name: '陈先生',
    contact: '微信：chen-mountain',
    message: '黑木耳冬耳和春耳口感区别大吗？',
    status: '未回复',
    reply: '',
    createdAt: '2026-04-10 18:40',
  },
]
