export const siteConfig = {
  brandName: '山野本味',
  tagline: '做茶四十余年，种植木耳四十余年',
  phone: '131-3764-2260',
  wechat: 'liushoufu13137642260',
  wechatQr: '/images/wechat-qr.svg',
  features: {
    showPrices: false,
  },
}

export const heroSlides = [
  {
    id: 'tea',
    title: '高山绿茶，鲜爽回甘',
    description: '主推春茶系列，突出清明前、清明与谷雨茶的层次口感。',
    image: '/images/products/green-tea/IMG_20260317_165714.jpg',
    productSlug: 'gaoshan-mingqian-lvcha',
  },
  {
    id: 'fungus',
    title: '椴木黑木耳，肉厚脆嫩',
    description: '春耳与冬耳分季精选，兼顾日常采购与送礼场景。',
    image: '/images/products/green-tea/IMG_20260317_165716.jpg',
    productSlug: 'duanmu-chuner-hei-muer',
  },
  {
    id: 'gift',
    title: '山野副产，一站了解',
    description: '葛根粉、橡子粉、茶油与农家土鸡蛋，满足多种家庭需求。',
    image: '/images/products/green-tea/IMG_20260317_165718.jpg',
    productSlug: 'cold-pressed-tea-oil',
  },
]

export const categories = [
  {
    id: 'green-tea',
    name: '绿茶',
    description: '按采摘时间分类，突出春茶鲜度与香气层次。',
    tags: ['清明前', '清明', '谷雨'],
  },
  {
    id: 'black-fungus',
    name: '椴木黑木耳',
    description: '按季节分类，突出春耳与冬耳的口感差异。',
    tags: ['春耳', '冬耳'],
  },
  {
    id: 'kudzu',
    name: '葛根粉',
    description: '细腻顺滑，适合冲调和家常滋补。',
    tags: ['冲调', '细粉'],
  },
  {
    id: 'acorn',
    name: '橡子粉',
    description: '地方特色风味，适合山野食品展示。',
    tags: ['山野', '风味'],
  },
  {
    id: 'tea-oil',
    name: '茶油',
    description: '冷榨清香，适合厨房与礼盒搭配。',
    tags: ['冷榨', '清香'],
  },
  {
    id: 'eggs',
    name: '农家土鸡蛋',
    description: '自然喂养，新鲜直供，适合家庭采购。',
    tags: ['农家', '新鲜'],
  },
]

export const products = [
  {
    id: 'p1',
    slug: 'gaoshan-mingqian-lvcha',
    name: '高山明前绿茶',
    category: '绿茶',
    subcategory: '清明前',
    summary: '芽叶细嫩，香气清扬，适合作为高端自饮和礼赠首选。',
    description: '精选高山茶园头采鲜叶，冲泡后汤色清亮，入口鲜爽回甘。',
    specifications: ['500g / 盒', '250g / 礼盒', '冷藏保存更佳'],
    sellingPoints: ['头采鲜叶', '嫩香明显', '礼盒包装可选'],
    price: '¥498 / 500g',
    showPrice: false,
    featured: true,
    hero: true,
    images: [
      '/images/products/green-tea/1196.jpg',
      '/images/products/green-tea/IMG_20260317_165714.jpg',
      '/images/products/green-tea/IMG_20260317_165716.jpg',
      '/images/products/green-tea/IMG_20260317_165718.jpg',
    ],
    packageImages: [
      '/images/packaging/tea/85c39460aa6eb174d99f8270338c9060.jpg',
    ],
  },
  {
    id: 'p2',
    slug: 'gaoshan-qingming-lvcha',
    name: '高山清明绿茶',
    category: '绿茶',
    subcategory: '清明',
    summary: '鲜爽与耐泡度兼顾，适合日常待客与办公室冲泡。',
    description: '在清明时段采摘，茶香持久，汤感更饱满，兼顾性价比与品质感。',
    specifications: ['250g / 袋', '500g / 经济装'],
    sellingPoints: ['香气持久', '耐泡度好', '日常饮用友好'],
    price: '¥198 / 250g',
    showPrice: false,
    featured: true,
    hero: false,
    images: [
      '/images/products/green-tea/1196.jpg',
      '/images/products/green-tea/IMG_20260317_165714.jpg',
      '/images/products/green-tea/IMG_20260317_165716.jpg',
      '/images/products/green-tea/IMG_20260317_165718.jpg',
    ],
    packageImages: [
      '/images/packaging/tea/85c39460aa6eb174d99f8270338c9060.jpg',
    ],
  },
  {
    id: 'p3',
    slug: 'guyu-lvcha',
    name: '谷雨鲜绿茶',
    category: '绿茶',
    subcategory: '谷雨',
    summary: '口粮级好茶，香气温润，适合长期回购。',
    description: '谷雨时节采摘，滋味醇和，适合家庭常备。',
    specifications: ['250g / 袋'],
    sellingPoints: ['口感醇和', '适合常饮', '性价比高'],
    price: '¥128 / 250g',
    showPrice: false,
    featured: false,
    hero: false,
    images: [
      '/images/products/green-tea/1196.jpg',
      '/images/products/green-tea/IMG_20260317_165714.jpg',
      '/images/products/green-tea/IMG_20260317_165716.jpg',
      '/images/products/green-tea/IMG_20260317_165718.jpg',
    ],
    packageImages: [
      '/images/packaging/tea/85c39460aa6eb174d99f8270338c9060.jpg',
    ],
  },
  {
    id: 'p4',
    slug: 'duanmu-chuner-hei-muer',
    name: '椴木春耳黑木耳',
    category: '椴木黑木耳',
    subcategory: '春耳',
    summary: '耳片舒展，肉质弹嫩，适合凉拌和家常烹饪。',
    description: '春季自然生长，朵型匀整，泡发率好，口感脆爽。',
    specifications: ['250g / 袋', '500g / 袋'],
    sellingPoints: ['泡发率高', '耳片完整', '家庭装友好'],
    price: '¥168 / 250g',
    showPrice: false,
    featured: true,
    hero: true,
    images: [
      '/images/products/green-tea/1196.jpg',
      '/images/products/green-tea/IMG_20260317_165714.jpg',
      '/images/products/green-tea/IMG_20260317_165716.jpg',
      '/images/products/green-tea/IMG_20260317_165718.jpg',
    ],
    packageImages: [
      '/images/packaging/tea/85c39460aa6eb174d99f8270338c9060.jpg',
    ],
  },
  {
    id: 'p5',
    slug: 'duanmu-donger-hei-muer',
    name: '椴木冬耳黑木耳',
    category: '椴木黑木耳',
    subcategory: '冬耳',
    summary: '肉厚紧实，适合炖煮和礼盒搭配。',
    description: '冬季采收，生长周期更长，口感更厚实，适合品质型客户。',
    specifications: ['250g / 礼盒', '500g / 礼盒'],
    sellingPoints: ['肉厚紧实', '礼盒感强', '炖煮表现佳'],
    price: '¥218 / 250g',
    showPrice: false,
    featured: true,
    hero: false,
    images: ['/images/hero-fungus.svg'],
    packageImages: ['/images/package-visual.svg'],
  },
  {
    id: 'p6',
    slug: 'mountain-kudzu-powder',
    name: '山野葛根粉',
    category: '葛根粉',
    subcategory: '',
    summary: '细粉易冲调，入口顺滑，适合作为伴手礼和日常冲饮。',
    description: '保留自然谷物风味，适合搭配蜂蜜、牛奶等多种饮用方式。',
    specifications: ['500g / 罐'],
    sellingPoints: ['冲调方便', '口感细腻', '家庭常备'],
    price: '¥88 / 500g',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/hero-gift.svg'],
    packageImages: ['/images/package-visual.svg'],
  },
  {
    id: 'p7',
    slug: 'mountain-acorn-powder',
    name: '山野橡子粉',
    category: '橡子粉',
    subcategory: '',
    summary: '地方特色风味，适合特色饮食体验和伴手礼。',
    description: '风味质朴，适合做地方风味食品或冲调饮品。',
    specifications: ['500g / 罐'],
    sellingPoints: ['山野风味', '地方特色', '伴手礼友好'],
    price: '¥96 / 500g',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/hero-gift.svg'],
    packageImages: ['/images/package-visual.svg'],
  },
  {
    id: 'p8',
    slug: 'cold-pressed-tea-oil',
    name: '冷榨山茶油',
    category: '茶油',
    subcategory: '',
    summary: '清香不腻，适合高品质厨房和礼盒组合。',
    description: '精选油茶籽冷榨而成，保留清香，适合凉拌和清炒。',
    specifications: ['500ml / 瓶', '1L / 礼盒'],
    sellingPoints: ['冷榨工艺', '清香自然', '礼盒可选'],
    price: '¥168 / 500ml',
    showPrice: false,
    featured: false,
    hero: true,
    images: ['/images/hero-gift.svg'],
    packageImages: ['/images/package-visual.svg'],
  },
  {
    id: 'p9',
    slug: 'farm-eggs',
    name: '农家土鸡蛋',
    category: '农家土鸡蛋',
    subcategory: '',
    summary: '自然喂养，蛋黄浓郁，适合家庭长期采购。',
    description: '来自农家散养环境，新鲜发货，适合家庭餐桌和节日走亲访友。',
    specifications: ['30 枚 / 箱', '60 枚 / 箱'],
    sellingPoints: ['农家散养', '新鲜发货', '蛋香浓郁'],
    price: '¥78 / 30枚',
    showPrice: false,
    featured: false,
    hero: false,
    images: ['/images/hero-gift.svg'],
    packageImages: ['/images/package-visual.svg'],
  },
]

export const storyHighlights = [
  {
    title: '做茶 40 余年',
    description: '坚持山场管理、时令采摘与传统制茶经验，保留绿茶应有的鲜爽层次。',
  },
  {
    title: '种植木耳 40 余年',
    description: '坚持椴木自然生长与分季采收，兼顾口感、泡发率和稳定供应。',
  },
  {
    title: '原产地直供',
    description: '从山场到包装更短链路，让客户更容易判断品质与来源。',
  },
]

export const originStories = [
  {
    title: '茶山环境',
    description: '山间云雾、昼夜温差和高海拔环境，形成了绿茶鲜爽回甘的基础。',
    image: '/images/products/green-tea/1172.jpg',
  },
  {
    title: '木耳种植',
    description: '椴木培植和分季管理，让木耳在自然环境中缓慢生长，口感更扎实。',
    image: '/images/products/green-tea/1172.jpg',
  },
]

export const packagingShowcase = [
  {
    title: '茶叶礼盒包装',
    image: '/images/packaging/tea/d66a27efd982925fffe1d7ac30ab8629.jpg',
    description: '适合送礼和商务场景，保持质朴中带品质感。',
  },
  {
    title: '木耳礼袋包装',
    image: '/images/packaging/tea/f51ccba60ae1dd8e867d76c6b76a9805.jpg',
    description: '强调简洁和识别度，适合线上展示和线下发货。',
  },
  {
    title: '副产礼品包装',
    image: '/images/packaging/tea/fa8dd38d7e383ba6726c4ac8c3d58b38.jpg',
    description: '适合茶油、葛根粉等组合搭配，便于节日伴手礼呈现。',
  },
]

export const defaultInquiries = [
  {
    id: 'inq-demo-1',
    name: '周女士',
    contact: '139****2608',
    product: '高山明前绿茶',
    message: '想了解礼盒规格和起订量。',
    createdAt: '2026-04-11 09:20',
  },
]

export const defaultMessages = [
  {
    id: 'msg-demo-1',
    name: '陈先生',
    contact: '微信：chen-mountain',
    message: '黑木耳冬耳和春耳口感区别大吗？',
    status: '未回复',
    reply: '',
    createdAt: '2026-04-10 18:40',
  },
]
